app:
  log:
    library: zap
    level: DEBUG
  server:
    port: "9596"

redis:
  test: false
  addr: "localhost:6379"
  password: ""

velog:
  url: "https://velog.io/"
  api_url: "https://v2.velog.io/graphql"
